version: '3'

services:
  speech-service:
    build:
      context: .
    volumes:
      -  ./src/:/src/
    command: python main.py
    env_file:
      - .env.dev
    networks:
      - chack-check-network

networks:
  chack-check-network:
    name: chack-check-network
    external: true